# 一、Python基础

在生成一个数字序列的时候，在Python中可以如下写出：

In [1]:
L=[]
def my_func(x):
    return 2*x
for i in range(5):
    L.append(my_func(i))

In [2]:
L

[0, 2, 4, 6, 8]

事实上可以利用列表推导式进行写法上的简化,类似于函数表达式加定义域

In [4]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

列表的多层嵌套

In [5]:
[m+'_'+n for m in ['a','b'] for n in ['c','d']]

['a_c', 'a_d', 'b_c', 'b_d']

带有if的条件赋值

In [8]:
value='cat' if 2>1 else 'dog'
value

'cat'

In [15]:
[i if i>0 else i+2 for i in range(-3,5)]

[-1, 0, 1, 2, 1, 2, 3, 4]

匿名函数与map方法

In [18]:
multi_para_func = lambda a,b: a+b
multi_para_func(1,2)

3

In [19]:
[(lambda x:2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [20]:
list(map(lambda x:2*x,range(5)))#map返回map类型对象，需要通过list转为列表：

[0, 2, 4, 6, 8]

In [21]:
list(map(lambda x,y:str(x)+y,range(5),['a','b','c','d','e']))

['0a', '1b', '2c', '3d', '4e']

zip对象与enumerate方法

In [23]:
L1,L2,L3 = list('abc'),list('def'),list('hij')
list(zip(L1,L2,L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [24]:
tuple(zip(L1,L2,L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [25]:
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)

a d h
b e i
c f j


In [28]:
L=list('a,b,c,d')
for index,value in enumerate(L):#enumerate是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号
    print(index,value)

0 a
1 ,
2 b
3 ,
4 c
5 ,
6 d


In [30]:
for index,value in zip(range(len(L)),L):
    print(index,value)

0 a
1 ,
2 b
3 ,
4 c
5 ,
6 d


In [31]:
dict(zip(L1,L2))#需要建立两个列表的字典映射，可以利用zip对象

{'a': 'd', 'b': 'e', 'c': 'f'}

In [32]:
# *和zip联合使用来进行解压操作
zipped=list(zip(L1,L2,L3))
print(zipped,L1)

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')] ['a', 'b', 'c']


In [33]:
list(zip(*zipped))

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

# 二、Numpy基础

In [1]:
import numpy as np
np.array([1,2,3])#通过array传入列表构造

array([1, 2, 3])

In [2]:
#等差序列: np.linspace np.arange
np.linspace(1,5,11)#起始、终止(包含)、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [5]:
np.arange(1,5,3)#起始、终止(不包括)、步长

array([1, 4])

特殊矩阵：zeros,eye,full

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.eye(3,k=2)#k表示偏主对角线k个单位的伪单位矩阵

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [12]:
np.full((2,3),[1,2,3])#通过传入列表填充每列的值

array([[1, 2, 3],
       [1, 2, 3]])

随机矩阵：np.random
rand,randn,randint,choice分别表示0-1均匀分布的随机数组、标准正态分布的随机数组、随机整数组合随机列表抽样

In [13]:
#服从区间a到b的均匀分布：
a,b=5,15
(b-a)*np.random.rand(3)+a

array([10.65130509, 13.17131955, 14.31089512])

In [14]:
#对于服从方差为 σ2 均值为 μ 的一元正态分布可以如下生成：
sigma,mu=2.5,3
mu+np.random.randn(3)*sigma

array([ 1.47317973, -0.10703095, -1.79194798])

In [15]:
np.random.randint(5,15,(2,2))#生成5到15(不包含)的随机整数

array([[5, 7],
       [8, 8]])

In [24]:
np.random.seed(0)#随机数种子可以固定随机数的输出结果
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [25]:
#T 转置、r_,c_分别表示上下合并row和左右合并column 针对二维数组
np.r_[np.zeros((3,4)),np.eye(4,k=2)]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
#一维和二维合并的时候，把一维看做列向量
np.c_[np.random.rand(5),np.zeros((5,2))]

array([[0.64589411, 0.        , 0.        ],
       [0.43758721, 0.        , 0.        ],
       [0.891773  , 0.        , 0.        ],
       [0.96366276, 0.        , 0.        ],
       [0.38344152, 0.        , 0.        ]])

In [27]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,1],[2,2],[3,3]])
a@b

array([[14, 14],
       [32, 32]])

In [38]:
a=np.array([[-2,-5,0,1,3,-1],[1,5,9,-6,0,66]])
a.argmax()#axis=0表示列的统计，1表示行的统计

11

## Ex1

In [12]:
import numpy as np
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res=[[sum([M1[i][k]*M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]
np.array(res)

array([[0.68933624, 0.10871425, 1.00149096, 0.99147766],
       [0.25954632, 0.40860795, 0.58775327, 0.29316761]])

## Ex2

In [17]:
A = np.arange(1,10).reshape(3,-1)
B = A*(1/A).sum(1).reshape(-1,1)

(3,)

## Ex3

In [35]:
 np.random.seed(0)
 A = np.random.randint(10, 20, (8, 5))
#  a=A.sum(1)
#  b=A.sum(0)
#  sumA=A.sum()
#  B=[[a[i]*b[j]/sumA for j in range(A.shape[1])] for i in range(A.shape[0])]
#  ((A-B)*(A-B)/B).sum()
B = A.sum(0)*A.sum(1).reshape(-1, 1)/A.sum()
res = ((A-B)**2/B).sum()
res

11.842696601945802

## Ex4

In [2]:
import numpy as np
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
(((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum()

100566

## Ex5

In [24]:
f = lambda x:np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()#合并操作，一维数组看作是一列
f([1,2,5,6,7])

array([0.28297932, 0.32522514, 0.49396892, 0.73120047, 0.01495998,
       5.        ])